import { LaboratoryOrderModel } from "../../models/laboratoryOrderModel"

export class LaboratoryOrderEntity {
	constructor(
    wbc:boolean,
    Hgn:boolean,
    ESR:boolean,
    BF:boolean,
    bloodGroup_RHType:boolean,
    bloodMorphology:boolean,
    neutrophil:boolean,
    eosinophil:boolean,
    lymphocyte:boolean,
    monocyte:boolean,
    Basophil:boolean,
    FBS_RBS:boolean,
    sgot:boolean,
    sgpt:boolean,
    totalProtien:boolean,
    albumin:boolean,
    glucose:boolean,
    ketone:boolean,
    blood:boolean,
    leukocyte:boolean,
    bilirubin:boolean,
    urobilin:boolean,
    PH:boolean,
    microscopic:boolean,
    widal:boolean,
    weilFelix:boolean,
    VDHL_EPR:boolean,
    Rf:boolean,
    HBsAg:boolean,
    Aso:boolean,
    PICT:boolean,
    HCV:boolean,
    wetMount:boolean,
    gramStain:boolean,
    AFBStain:boolean,
    pregnancyTest:boolean,
    KOH:boolean,
    SKINSmear:boolean,
    protein:boolean,
    WBC:boolean,
    DiffCount:boolean,
    stoolExam:boolean,
    HIV:boolean,
    xRay:boolean,
    ultraSound:boolean,
  ) {
  }

  public static fromDatabase(obj: LaboratoryOrderModel): LaboratoryOrderEntity {
    const {
      wbc,
      Hgn,
      ESR,
      BF,
      bloodGroup_RHType,
      bloodMorphology,
      neutrophil,
      eosinophil,
      lymphocyte,
      monocyte,
      Basophil,
      FBS_RBS,
      sgot,
      sgpt,
      totalProtien,
      albumin,
      glucose,
      ketone,
      blood,
      leukocyte,
      bilirubin,
      urobilin,
      PH,
      microscopic,
      widal,
      weilFelix,
      VDHL_EPR,
      Rf,
      HBsAg,
      Aso,
      PICT,
      HCV,
      wetMount,
      gramStain,
      AFBStain,
      pregnancyTest,
      KOH,
      SKINSmear,
      protein,
      WBC,
      DiffCount,
      stoolExam,
      HIV,
      xRay,
      ultraSound,
    } = obj;

    return new LaboratoryOrderEntity(
      wbc as boolean,
      Hgn as boolean,
      ESR as boolean,
      BF as boolean,
      bloodGroup_RHType as boolean,
      bloodMorphology as boolean,
      neutrophil as boolean,
      eosinophil as boolean,
      lymphocyte as boolean,
      monocyte as boolean,
      Basophil as boolean,
      FBS_RBS as boolean,
      sgot as boolean,
      sgpt as boolean,
      totalProtien as boolean,
      albumin as boolean,
      glucose as boolean,
      ketone as boolean,
      blood as boolean,
      leukocyte as boolean,
      bilirubin as boolean,
      urobilin as boolean,
      PH as boolean,
      microscopic as boolean,
      widal as boolean,
      weilFelix as boolean,
      VDHL_EPR as boolean,
      Rf as boolean,
      HBsAg as boolean,
      Aso as boolean,
      PICT as boolean,
      HCV as boolean,
      wetMount as boolean,
      gramStain as boolean,
      AFBStain as boolean,
      pregnancyTest as boolean,
      KOH as boolean,
      SKINSmear as boolean,
      protein as boolean,
      WBC as boolean,
      DiffCount as boolean,
      stoolExam as boolean,
      HIV as boolean,
      xRay as boolean,
      ultraSound as boolean,
    )
  }
}