version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg_database

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
      image: redis:alpine
      container_name: redis-alpine
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV= development
    depends_on:
      - redis
      - postgres
  
  # RedisInsight Service
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight_container
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/db

  
  # pgAdmin Service (for managing your PostgreSQL database)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
  pgadmin_data:
