version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  app:
    build: .
    ports:
      - "${APP_PORT:-4000}:4000"
    env_file:
      - .env
    volumes:
      - .:/app 
    # environment:
    #   - NODE_ENV=production 
    depends_on:
      - redis
      - postgres
    networks:
      - my_network

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   container_name: redisinsight_container
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "${REDISINSIGHT_PORT:-8001}:8001"
  #   depends_on:
  #     - redis
  #   volumes:
  #     - redisinsight_data:/db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
  pgadmin_data:

networks:
  my_network: