import { LaboratoryResultModel } from "../laboratoryResultModel";

export class LaboratoryResultEntity {
	constructor(
    wbc: string,
    Hgn: string,
    ESR: string,
    BF: string,
    bloodGroup_RHType: string,
    bloodMorphology: string,
    neutrophil: string,
    eosinophil: string,
    lymphocyte: string,
    monocyte: string,
    Basophil: string,
    FBS_RBS: string,
    sgot: string,
    sgpt: string,
    totalProtien: string,
    albumin: string,
    glucose: string,
    ketone: string,
    blood: string,
    leukocyte: string,
    bilirubin: string,
    urobilin: string,
    PH: string,
    microscopic: string,
    widal: string,
    weilFelix: string,
    VDHL_EPR: string,
    Rf: string,
    HBsAg: string,
    Aso: string,
    PICT: string,
    HCV: string,
    wetMount: string,
    gramStain: string,
    AFBStain: string,
    pregnancyTest: string,
    KOH: string,
    SKINSmear: string,
    protein: string,
    gramStam: string,
    AFBStam: string,
    WBC: string,
    DiffCount: string,
    stoolExam: string,
    HIV: string,
    xRay: number,
    ultraSound: number,
  ) {
  }

  public static fromDatabase(obj: LaboratoryResultModel): LaboratoryResultEntity {
    const {
      wbc,
      Hgn,
      ESR,
      BF,
      bloodGroup_RHType,
      bloodMorphology,
      neutrophil,
      eosinophil,
      lymphocyte,
      monocyte,
      Basophil,
      FBS_RBS,
      sgot,
      sgpt,
      totalProtien,
      albumin,
      glucose,
      ketone,
      blood,
      leukocyte,
      bilirubin,
      urobilin,
      PH,
      microscopic,
      widal,
      weilFelix,
      VDHL_EPR,
      Rf,
      HBsAg,
      Aso,
      PICT,
      HCV,
      wetMount,
      gramStain,
      AFBStain,
      pregnancyTest,
      KOH,
      SKINSmear,
      protein,
      gramStam,
      AFBStam,
      WBC,
      DiffCount,
      stoolExam,
      HIV,
      xRay,
      ultraSound,
    } = obj;

    return new LaboratoryResultEntity(
       wbc as string,
        Hgn as string,
        ESR as string,
        BF as string,
        bloodGroup_RHType as string,
        bloodMorphology as string,
        neutrophil as string,
        eosinophil as string,
        lymphocyte as string,
        monocyte as string,
        Basophil as string,
        FBS_RBS as string,
        sgot as string,
        sgpt as string,
        totalProtien as string,
        albumin as string,
        glucose as string,
        ketone as string,
        blood as string,
        leukocyte as string,
        bilirubin as string,
        urobilin as string,
        PH as string,
        microscopic as string,
        widal as string,
        weilFelix as string,
        VDHL_EPR as string,
        Rf as string,
        HBsAg as string,
        Aso as string,
        PICT as string,
        HCV as string,
        wetMount as string,
        gramStain as string,
        AFBStain as string,
        pregnancyTest as string,
        KOH as string,
        SKINSmear as string,
        protein as string,
        gramStam as string,
        AFBStam as string,
        WBC as string,
        DiffCount as string,
        stoolExam as string,
        HIV as string,
        xRay as number,
        ultraSound as number,
    )
  }
}